-- Drop the waitlist table, which is orphaned on any database that predates the
-- removal of POST /v1/waitlist.
--
-- WHY THIS MIGRATION EXISTS AT ALL
--
-- The waitlist surface was removed in 16c0553 by DELETING its creating
-- migration (015_waitlist.sql) rather than by writing a drop. That works for a
-- fresh install -- there is no 015, so the table is never created -- but it
-- does nothing for a database that already applied 015. apply_migrations.py
-- records applied filenames and skips them permanently, so removing the file
-- neither re-runs nor reverses anything. The table simply stays, forever, on
-- every pre-existing install, while new installs never have it.
--
-- That is the exact divergence 021's own header warned about for
-- agent_category_scores. The same reasoning applies here and was missed:
-- deleting an applied migration makes new and existing databases diverge
-- silently. A schema difference that depends on when an operator first
-- installed is not a schema; it is a coin flip.
--
-- DATA IMPACT -- READ BEFORE APPLYING
--
-- Unlike 021, this table is NOT provably empty. agent_category_scores had no
-- writer anywhere in the tree; waitlist had a real writer -- the public,
-- unauthenticated POST /v1/waitlist endpoint -- so an operator who ran a
-- pre-removal build with that endpoint reachable could hold captured email
-- addresses here.
--
-- In practice the endpoint only ever existed on builds of a hosted product
-- that was never launched, so the expected row count is zero. If you are
-- upgrading a long-lived instance and want to be certain, check before you
-- run this:
--
--     SELECT count(*) FROM waitlist;
--
-- and dump it first if that returns anything you care about:
--
--     pg_dump -U conclave -t waitlist conclave > waitlist-backup.sql
--
-- Dropping the table also drops its PRIMARY KEY, its UNIQUE constraint on
-- email_norm, and idx_waitlist_ip_recent. The explicit DROP INDEX below is
-- belt-and-braces for the case where the index outlived its table.

DROP INDEX IF EXISTS idx_waitlist_ip_recent;
DROP TABLE IF EXISTS waitlist;
